version: '3'

services:
  iptables-web-dev:
    image: iptables-web-dev:1.0
    build:
      context: ./
    container_name: iptables-web-dev
    tty: true
    privileged: true
    volumes:
      - ../:/root/src
    ports:
      - "1337:1337"
